/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          strong: "var(--stack-semantic-brand-strong)",
          DEFAULT: "var(--stack-semantic-brand-default)",
          subtle: "var(--stack-semantic-brand-subtle)",
          subtler: "var(--stack-semantic-brand-subtler)",
          subtlest: "var(--stack-semantic-brand-subtlest)",
        },
        text: {
          primary: "var(--stack-semantic-text-primary)",
          secondary: "var(--stack-semantic-text-secondary)",
          tertiary: "var(--stack-semantic-text-tertiary)",
          quaternary: "var(--stack-semantic-text-quaternary)",
          inverse: "var(--stack-semantic-text-inverse)",
        },
        icon: {
          primary: "var(--stack-semantic-icon-primary)",
          secondary: "var(--stack-semantic-icon-secondary)",
          tertiary: "var(--stack-semantic-icon-tertiary)",
          quaternary: "var(--stack-semantic-icon-quaternary)",
          inverse: "var(--stack-semantic-icon-inverse)",
        },
        status: {
          success: {
            DEFAULT: "var(--stack-semantic-status-success-default)",
            subtle: "var(--stack-semantic-status-success-subtle)",
            subtler: "var(--stack-semantic-status-success-subtler)",
            subtlest: "var(--stack-semantic-status-success-subtlest)",
          },
          warning: {
            DEFAULT: "var(--stack-semantic-status-warning-default)",
            subtle: "var(--stack-semantic-status-warning-subtle)",
            subtler: "var(--stack-semantic-status-warning-subtler)",
            subtlest: "var(--stack-semantic-status-warning-subtlest)",
          },
          error: {
            DEFAULT: "var(--stack-semantic-status-error-default)",
            subtle: "var(--stack-semantic-status-error-subtle)",
            subtler: "var(--stack-semantic-status-error-subtler)",
            subtlest: "var(--stack-semantic-status-error-subtlest)",
          },
          processing: {
            DEFAULT: "var(--stack-semantic-status-processing-default)",
            subtle: "var(--stack-semantic-status-processing-subtle)",
            subtler: "var(--stack-semantic-status-processing-subtler)",
            subtlest: "var(--stack-semantic-status-processing-subtlest)",
          },
        },
        background: {
          DEFAULT: "var(--stack-semantic-background-default)",
          subtle: "var(--stack-semantic-background-subtle)",
        },
        line: {
          clickable: "var(--stack-semantic-line-clickable)",
          nonClickable: "var(--stack-semantic-line-nonClickable)",
        },
        dimm: {
          DEFAULT: "var(--stack-semantic-dimm-default)",
        },
        // Primitive Colors
        neutral: {
          0: "var(--stack-primitive-neutral-0)",
          5: "var(--stack-primitive-neutral-5)",
          10: "var(--stack-primitive-neutral-10)",
          20: "var(--stack-primitive-neutral-20)",
          30: "var(--stack-primitive-neutral-30)",
          40: "var(--stack-primitive-neutral-40)",
          50: "var(--stack-primitive-neutral-50)",
          60: "var(--stack-primitive-neutral-60)",
          70: "var(--stack-primitive-neutral-70)",
          80: "var(--stack-primitive-neutral-80)",
          90: "var(--stack-primitive-neutral-90)",
          95: "var(--stack-primitive-neutral-95)",
          100: "var(--stack-primitive-neutral-100)",
        },
        "deep-red": {
          5: "var(--stack-primitive-deepRed-5)",
          10: "var(--stack-primitive-deepRed-10)",
          20: "var(--stack-primitive-deepRed-20)",
          30: "var(--stack-primitive-deepRed-30)",
          40: "var(--stack-primitive-deepRed-40)",
          50: "var(--stack-primitive-deepRed-50)",
          60: "var(--stack-primitive-deepRed-60)",
          70: "var(--stack-primitive-deepRed-70)",
          80: "var(--stack-primitive-deepRed-80)",
          90: "var(--stack-primitive-deepRed-90)",
          100: "var(--stack-primitive-deepRed-100)",
        },
        red: {
          5: "var(--stack-primitive-red-5)",
          10: "var(--stack-primitive-red-10)",
          20: "var(--stack-primitive-red-20)",
          30: "var(--stack-primitive-red-30)",
          40: "var(--stack-primitive-red-40)",
          50: "var(--stack-primitive-red-50)",
          60: "var(--stack-primitive-red-60)",
          70: "var(--stack-primitive-red-70)",
          80: "var(--stack-primitive-red-80)",
          90: "var(--stack-primitive-red-90)",
          100: "var(--stack-primitive-red-100)",
        },
        orange: {
          5: "var(--stack-primitive-orange-5)",
          10: "var(--stack-primitive-orange-10)",
          20: "var(--stack-primitive-orange-20)",
          30: "var(--stack-primitive-orange-30)",
          40: "var(--stack-primitive-orange-40)",
          50: "var(--stack-primitive-orange-50)",
          60: "var(--stack-primitive-orange-60)",
          70: "var(--stack-primitive-orange-70)",
          80: "var(--stack-primitive-orange-80)",
          90: "var(--stack-primitive-orange-90)",
          100: "var(--stack-primitive-orange-100)",
        },
        yellow: {
          5: "var(--stack-primitive-yellow-5)",
          10: "var(--stack-primitive-yellow-10)",
          20: "var(--stack-primitive-yellow-20)",
          30: "var(--stack-primitive-yellow-30)",
          40: "var(--stack-primitive-yellow-40)",
          50: "var(--stack-primitive-yellow-50)",
          60: "var(--stack-primitive-yellow-60)",
          70: "var(--stack-primitive-yellow-70)",
          80: "var(--stack-primitive-yellow-80)",
          90: "var(--stack-primitive-yellow-90)",
          100: "var(--stack-primitive-yellow-100)",
        },
        green: {
          5: "var(--stack-primitive-green-5)",
          10: "var(--stack-primitive-green-10)",
          20: "var(--stack-primitive-green-20)",
          30: "var(--stack-primitive-green-30)",
          40: "var(--stack-primitive-green-40)",
          50: "var(--stack-primitive-green-50)",
          60: "var(--stack-primitive-green-60)",
          70: "var(--stack-primitive-green-70)",
          80: "var(--stack-primitive-green-80)",
          90: "var(--stack-primitive-green-90)",
          100: "var(--stack-primitive-green-100)",
        },
        mint: {
          5: "var(--stack-primitive-mint-5)",
          10: "var(--stack-primitive-mint-10)",
          20: "var(--stack-primitive-mint-20)",
          30: "var(--stack-primitive-mint-30)",
          40: "var(--stack-primitive-mint-40)",
          50: "var(--stack-primitive-mint-50)",
          60: "var(--stack-primitive-mint-60)",
          70: "var(--stack-primitive-mint-70)",
          80: "var(--stack-primitive-mint-80)",
          90: "var(--stack-primitive-mint-90)",
          100: "var(--stack-primitive-mint-100)",
        },
        blue: {
          5: "var(--stack-primitive-blue-5)",
          10: "var(--stack-primitive-blue-10)",
          20: "var(--stack-primitive-blue-20)",
          30: "var(--stack-primitive-blue-30)",
          40: "var(--stack-primitive-blue-40)",
          50: "var(--stack-primitive-blue-50)",
          60: "var(--stack-primitive-blue-60)",
          70: "var(--stack-primitive-blue-70)",
          80: "var(--stack-primitive-blue-80)",
          90: "var(--stack-primitive-blue-90)",
          100: "var(--stack-primitive-blue-100)",
        },
        "deep-blue": {
          5: "var(--stack-primitive-deepBlue-5)",
          10: "var(--stack-primitive-deepBlue-10)",
          20: "var(--stack-primitive-deepBlue-20)",
          30: "var(--stack-primitive-deepBlue-30)",
          40: "var(--stack-primitive-deepBlue-40)",
          50: "var(--stack-primitive-deepBlue-50)",
          60: "var(--stack-primitive-deepBlue-60)",
          70: "var(--stack-primitive-deepBlue-70)",
          80: "var(--stack-primitive-deepBlue-80)",
          90: "var(--stack-primitive-deepBlue-90)",
          100: "var(--stack-primitive-deepBlue-100)",
        },
        purple: {
          5: "var(--stack-primitive-purple-5)",
          10: "var(--stack-primitive-purple-10)",
          20: "var(--stack-primitive-purple-20)",
          30: "var(--stack-primitive-purple-30)",
          40: "var(--stack-primitive-purple-40)",
          50: "var(--stack-primitive-purple-50)",
          60: "var(--stack-primitive-purple-60)",
          70: "var(--stack-primitive-purple-70)",
          80: "var(--stack-primitive-purple-80)",
          90: "var(--stack-primitive-purple-90)",
          100: "var(--stack-primitive-purple-100)",
        },
        pink: {
          5: "var(--stack-primitive-pink-5)",
          10: "var(--stack-primitive-pink-10)",
          20: "var(--stack-primitive-pink-20)",
          30: "var(--stack-primitive-pink-30)",
          40: "var(--stack-primitive-pink-40)",
          50: "var(--stack-primitive-pink-50)",
          60: "var(--stack-primitive-pink-60)",
          70: "var(--stack-primitive-pink-70)",
          80: "var(--stack-primitive-pink-80)",
          90: "var(--stack-primitive-pink-90)",
          100: "var(--stack-primitive-pink-100)",
        },
        "neutral-white-alpha": {
          8: "var(--stack-primitive-neutralWhiteAlpha-8)",
          12: "var(--stack-primitive-neutralWhiteAlpha-12)",
          20: "var(--stack-primitive-neutralWhiteAlpha-20)",
        },
        "neutral-black-alpha": {
          0: "var(--stack-primitive-neutralBlackAlpha-0)",
          60: "var(--stack-primitive-neutralBlackAlpha-60)",
        },
        "neutral-blue-alpha": {
          8: "var(--stack-primitive-neutralBlueAlpha-8)",
          12: "var(--stack-primitive-neutralBlueAlpha-12)",
          15: "var(--stack-primitive-neutralBlueAlpha-15)",
        },
      },
      boxShadow: {
        "elevation-1": "var(--stack-semantic-shadow-elevation1)",
        "elevation-2": "var(--stack-semantic-shadow-elevation2)",
      },
      blur: {
        primary: "var(--stack-semantic-blur-primary)",
      },
      // button 스타일은 @apply나 components layer에서 정의하는 것이 좋습니다
    },
  },
  plugins: [],
};
